# Investigate the impact on speed of latency and packet loss using http/3 enabled servers and clients
version: '3'
services:
  server:
    build: server
    cap_add:
      - NET_ADMIN
    tmpfs:
      - /usr/local/nginx/html/tmp
    environment:
      - DATA_SIZE
  client:
    build: client
    tty: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - server
    environment:
      - NUMBER_OF_TESTS
      - MAX_DOWNLOAD_TIME
